output_dir: output

model:
  in_dim: 3
  emb_dim: 128
  ch_mult: 1
  T: 1000
  t_dim: 512
  c_dim: 512
  num_blocks: 3
  p_uncond: 0.2
data:
  path: /file/tian/data/imagenet/train
  batch_size: 96
  num_workers: 16
train:
  epochs: 1000000
  lr: 0.0002
  weight_decay: 1.e-3
  log_freq: 50
  sample_img_freq: 500
